version: '3'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    ports:  
      - "1433:1433"
    environment:
      SA_PASSWORD: "Root@123"
      ACCEPT_EULA: "Y"
    volumes: 
      - sqldata:/var/lib/mssqlql/data
  dapper-api:
    image: realdavis/aspnetcore-dapper:latest
    build:
        context: ../src
        dockerfile: ANCD.API/Dockerfile
    restart: always
    ports:
      - "7128:7128"            
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://*:7128
    depends_on:
      - sql-server

volumes:
  sqldata: